# Generated by Django 5.1.5 on 2025-01-29 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilemodel',
            name='birthday',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='nickname',
            field=models.CharField(blank=True, max_length=128, null=True, unique=True),
        ),
    ]
