# Generated by Django 5.1.5 on 2025-01-29 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_profilemodel_birthday_alter_usermodel_nickname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usermodel',
            old_name='account',
            new_name='profile',
        ),
    ]
