# Generated by Django 5.1.5 on 2025-02-05 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_account_usermodel_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='is_online',
            field=models.BooleanField(default=False),
        ),
    ]
