# Generated by Django 5.1.6 on 2025-02-25 18:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_usermodel_contacts_alter_usermodel_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvatarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, upload_to='image/')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avatar', to='users.profilemodel')),
            ],
            options={
                'db_table': 'avatar',
            },
        ),
    ]
