# Generated by Django 5.1.6 on 2025-02-25 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_avatarmodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='avatarmodel',
            old_name='avatar',
            new_name='image',
        ),
    ]
